package POJOs;
// Generated Sep 24, 2013 9:20:03 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Loaitaikhoan generated by hbm2java
 */
public class Loaitaikhoan  implements java.io.Serializable {


     private int maloaitaikhoan;
     private Serializable tenloaitaikhoan;
     private Set<Taikhoan> taikhoans = new HashSet<Taikhoan>(0);

    public Loaitaikhoan() {
    }

	
    public Loaitaikhoan(int maloaitaikhoan) {
        this.maloaitaikhoan = maloaitaikhoan;
    }
    public Loaitaikhoan(int maloaitaikhoan, Serializable tenloaitaikhoan, Set<Taikhoan> taikhoans) {
       this.maloaitaikhoan = maloaitaikhoan;
       this.tenloaitaikhoan = tenloaitaikhoan;
       this.taikhoans = taikhoans;
    }
   
    public int getMaloaitaikhoan() {
        return this.maloaitaikhoan;
    }
    
    public void setMaloaitaikhoan(int maloaitaikhoan) {
        this.maloaitaikhoan = maloaitaikhoan;
    }
    public Serializable getTenloaitaikhoan() {
        return this.tenloaitaikhoan;
    }
    
    public void setTenloaitaikhoan(Serializable tenloaitaikhoan) {
        this.tenloaitaikhoan = tenloaitaikhoan;
    }
    public Set<Taikhoan> getTaikhoans() {
        return this.taikhoans;
    }
    
    public void setTaikhoans(Set<Taikhoan> taikhoans) {
        this.taikhoans = taikhoans;
    }




}


